version: "3.9"
services:
  postgres:
    image: postgres:latest 
    ports:
      - 3307:3306
      - 5432:5432
    container_name: pg
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGADMIN_DEFAULT_EMAIL: example@example.com
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
